<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder {
	
	public function run() 
	{
		DB::table('countries')->truncate();

		$countries = 
		[

			[
				"name_en" => "Afghanistan",
				"name_es" => "Afganistán",
				"name_it" => "Afghanistan",
				"name_br" => "Afeganistão",
				"name_fr" => "Afghanistan",
				"alpha2Code" => "AF",
				"alpha3Code" => "AFG",
				"dialcode" => "93",
				"currenciesCode" => "AFN",
				"currenciesSymbol" => "؋",
				"flag" => "🇦🇫"
			],
			[
				"name_en" => "Åland Islands",
				"name_es" => "Alandia",
				"name_it" => "Isole Aland",
				"name_br" => "Ilhas de Aland",
				"name_fr" => "Åland",
				"alpha2Code" => "AX",
				"alpha3Code" => "ALA",
				"dialcode" => "358",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇦🇽"
			],
			[
				"name_en" => "Albania",
				"name_es" => "Albania",
				"name_it" => "Albania",
				"name_br" => "Albânia",
				"name_fr" => "Albanie",
				"alpha2Code" => "AL",
				"alpha3Code" => "ALB",
				"dialcode" => "355",
				"currenciesCode" => "ALL",
				"currenciesSymbol" => "L",
				"flag" => "🇦🇱"
			],
			[
				"name_en" => "Algeria",
				"name_es" => "Argelia",
				"name_it" => "Algeria",
				"name_br" => "Argélia",
				"name_fr" => "Algérie",
				"alpha2Code" => "DZ",
				"alpha3Code" => "DZA",
				"dialcode" => "213",
				"currenciesCode" => "DZD",
				"currenciesSymbol" => "د.ج",
				"flag" => "🇩🇿"
			],
			[
				"name_en" => "American Samoa",
				"name_es" => "Samoa Americana",
				"name_it" => "Samoa Americane",
				"name_br" => "Samoa Americana",
				"name_fr" => "Samoa américaines",
				"alpha2Code" => "AS",
				"alpha3Code" => "ASM",
				"dialcode" => "1684",
				"currenciesCode" => "USD",
				"currenciesSymbol" => "$",
				"flag" => "🇺🇸"
			],
			[
				"name_en" => "Andorra",
				"name_es" => "Andorra",
				"name_it" => "Andorra",
				"name_br" => "Andorra",
				"name_fr" => "Andorre",
				"alpha2Code" => "AD",
				"alpha3Code" => "AND",
				"dialcode" => "376",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇦🇩"
			],
			[
				"name_en" => "Angola",
				"name_es" => "Angola",
				"name_it" => "Angola",
				"name_br" => "Angola",
				"name_fr" => "Angola",
				"alpha2Code" => "AO",
				"alpha3Code" => "AGO",
				"dialcode" => "244",
				"currenciesCode" => "AOA",
				"currenciesSymbol" => "Kz",
				"flag" => "🇦🇴"
			],
			[
				"name_en" => "Anguilla",
				"name_es" => "Anguilla",
				"name_it" => "Anguilla",
				"name_br" => "Anguila",
				"name_fr" => "Anguilla",
				"alpha2Code" => "AI",
				"alpha3Code" => "AIA",
				"dialcode" => "1264",
				"currenciesCode" => "XCD",
				"currenciesSymbol" => "$",
				"flag" => "🇦🇮"
			],
			[
				"name_en" => "Antarctica",
				"name_es" => "Antártida",
				"name_it" => "Antartide",
				"name_br" => "Antártida",
				"name_fr" => "Antarctique",
				"alpha2Code" => "AQ",
				"alpha3Code" => "ATA",
				"dialcode" => "672",
				"currenciesCode" => "AUD",
				"currenciesSymbol" => "$",
				"flag" => "🇦🇶"
			],
			[
				"name_en" => "Antigua and Barbuda",
				"name_es" => "Antigua y Barbuda",
				"name_it" => "Antigua e Barbuda",
				"name_br" => "Antígua e Barbuda",
				"name_fr" => "Antigua-et-Barbuda",
				"alpha2Code" => "AG",
				"alpha3Code" => "ATG",
				"dialcode" => "1268",
				"currenciesCode" => "XCD",
				"currenciesSymbol" => "$",
				"flag" => "🇦🇬"
			],
			[
				"name_en" => "Argentina",
				"name_es" => "Argentina",
				"name_it" => "Argentina",
				"name_br" => "Argentina",
				"name_fr" => "Argentine",
				"alpha2Code" => "AR",
				"alpha3Code" => "ARG",
				"dialcode" => "54",
				"currenciesCode" => "ARS",
				"currenciesSymbol" => "$",
				"flag" => "🇦🇷"
			],
			[
				"name_en" => "Armenia",
				"name_es" => "Armenia",
				"name_it" => "Armenia",
				"name_br" => "Armênia",
				"name_fr" => "Arménie",
				"alpha2Code" => "AM",
				"alpha3Code" => "ARM",
				"dialcode" => "374",
				"currenciesCode" => "AMD",
				"currenciesSymbol" => "",
				"flag" => "🇦🇲"
			],
			[
				"name_en" => "Aruba",
				"name_es" => "Aruba",
				"name_it" => "Aruba",
				"name_br" => "Aruba",
				"name_fr" => "Aruba",
				"alpha2Code" => "AW",
				"alpha3Code" => "ABW",
				"dialcode" => "297",
				"currenciesCode" => "AWG",
				"currenciesSymbol" => "ƒ",
				"flag" => "🇦🇼"
			],
			[
				"name_en" => "Australia",
				"name_es" => "Australia",
				"name_it" => "Australia",
				"name_br" => "Austrália",
				"name_fr" => "Australie",
				"alpha2Code" => "AU",
				"alpha3Code" => "AUS",
				"dialcode" => "61",
				"currenciesCode" => "AUD",
				"currenciesSymbol" => "$",
				"flag" => "🇦🇺"
			],
			[
				"name_en" => "Austria",
				"name_es" => "Austria",
				"name_it" => "Austria",
				"name_br" => "áustria",
				"name_fr" => "Autriche",
				"alpha2Code" => "AT",
				"alpha3Code" => "AUT",
				"dialcode" => "43",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇦🇹"
			],
			[
				"name_en" => "Azerbaijan",
				"name_es" => "Azerbaiyán",
				"name_it" => "Azerbaijan",
				"name_br" => "Azerbaijão",
				"name_fr" => "Azerbaïdjan",
				"alpha2Code" => "AZ",
				"alpha3Code" => "AZE",
				"dialcode" => "994",
				"currenciesCode" => "AZN",
				"currenciesSymbol" => "",
				"flag" => "🇦🇿"
			],
			[
				"name_en" => "Bahamas",
				"name_es" => "Bahamas",
				"name_it" => "Bahamas",
				"name_br" => "Bahamas",
				"name_fr" => "Bahamas",
				"alpha2Code" => "BS",
				"alpha3Code" => "BHS",
				"dialcode" => "1242",
				"currenciesCode" => "BSD",
				"currenciesSymbol" => "$",
				"flag" => "🇧🇸"
			],
			[
				"name_en" => "Bahrain",
				"name_es" => "Bahrein",
				"name_it" => "Bahrein",
				"name_br" => "Bahrein",
				"name_fr" => "Bahreïn",
				"alpha2Code" => "BH",
				"alpha3Code" => "BHR",
				"dialcode" => "973",
				"currenciesCode" => "BHD",
				"currenciesSymbol" => ".د.ب",
				"flag" => "🇧🇸"
			],
			[
				"name_en" => "Bangladesh",
				"name_es" => "Bangladesh",
				"name_it" => "Bangladesh",
				"name_br" => "Bangladesh",
				"name_fr" => "Bangladesh",
				"alpha2Code" => "BD",
				"alpha3Code" => "BGD",
				"dialcode" => "880",
				"currenciesCode" => "BDT",
				"currenciesSymbol" => "৳",
				"flag" => "🇧🇩"
			],
			[
				"name_en" => "Barbados",
				"name_es" => "Barbados",
				"name_it" => "Barbados",
				"name_br" => "Barbados",
				"name_fr" => "Barbade",
				"alpha2Code" => "BB",
				"alpha3Code" => "BRB",
				"dialcode" => "1246",
				"currenciesCode" => "BBD",
				"currenciesSymbol" => "$",
				"flag" => "🇧🇧"
			],
			[
				"name_en" => "Belarus",
				"name_es" => "Bielorrusia",
				"name_it" => "Bielorussia",
				"name_br" => "Bielorrússia",
				"name_fr" => "Biélorussie",
				"alpha2Code" => "BY",
				"alpha3Code" => "BLR",
				"dialcode" => "375",
				"currenciesCode" => "BYN",
				"currenciesSymbol" => "Br",
				"flag" => "🇧🇾"
			],
			[
				"name_en" => "Belgium",
				"name_es" => "Bélgica",
				"name_it" => "Belgio",
				"name_br" => "Bélgica",
				"name_fr" => "Belgique",
				"alpha2Code" => "BE",
				"alpha3Code" => "BEL",
				"dialcode" => "32",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇧🇪"
			],
			[
				"name_en" => "Belize",
				"name_es" => "Belice",
				"name_it" => "Belize",
				"name_br" => "Belize",
				"name_fr" => "Belize",
				"alpha2Code" => "BZ",
				"alpha3Code" => "BLZ",
				"dialcode" => "501",
				"currenciesCode" => "BZD",
				"currenciesSymbol" => "$",
				"flag" => "🇧🇿"
			],
			[
				"name_en" => "Benin",
				"name_es" => "Benín",
				"name_it" => "Benin",
				"name_br" => "Benin",
				"name_fr" => "Bénin",
				"alpha2Code" => "BJ",
				"alpha3Code" => "BEN",
				"dialcode" => "229",
				"currenciesCode" => "XOF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇧🇯"
			],
			[
				"name_en" => "Bermuda",
				"name_es" => "Bermudas",
				"name_it" => "Bermuda",
				"name_br" => "Bermudas",
				"name_fr" => "Bermudes",
				"alpha2Code" => "BM",
				"alpha3Code" => "BMU",
				"dialcode" => "1441",
				"currenciesCode" => "BMD",
				"currenciesSymbol" => "$",
				"flag" => "🇧🇲"
			],
			[
				"name_en" => "Bhutan",
				"name_es" => "Bután",
				"name_it" => "Bhutan",
				"name_br" => "Butão",
				"name_fr" => "Bhoutan",
				"alpha2Code" => "BT",
				"alpha3Code" => "BTN",
				"dialcode" => "975",
				"currenciesCode" => "BTN",
				"currenciesSymbol" => "Nu.",
				"flag" => "🇧🇹"
			],
			[
				"name_en" => "Bolivia (Plurinational State of)",
				"name_es" => "Bolivia",
				"name_it" => "Bolivia",
				"name_br" => "Bolívia",
				"name_fr" => "Bolivie",
				"alpha2Code" => "BO",
				"alpha3Code" => "BOL",
				"dialcode" => "591",
				"currenciesCode" => "BOB",
				"currenciesSymbol" => "Bs.",
				"flag" => "🇧🇴"
			],
			[
				"name_en" => "Bonaire, Sint Eustatius and Saba",
				"name_es" => "Bonaire, San Eustaquio y Saba",
				"name_it" => "Bonaire, Saint-Eustache e Saba",
				"name_br" => "Bonaire",
				"name_fr" => "Bonaire, Saint-Eustache et Saba",
				"alpha2Code" => "BQ",
				"alpha3Code" => "BES",
				"dialcode" => "5997",
				"currenciesCode" => "USD",
				"currenciesSymbol" => "$",
				"flag" => ""
			],
			[
				"name_en" => "Bosnia and Herzegovina",
				"name_es" => "Bosnia y Herzegovina",
				"name_it" => "Bosnia ed Erzegovina",
				"name_br" => "Bósnia e Herzegovina",
				"name_fr" => "Bosnie-Herzégovine",
				"alpha2Code" => "BA",
				"alpha3Code" => "BIH",
				"dialcode" => "387",
				"currenciesCode" => "BAM",
				"currenciesSymbol" => "",
				"flag" => "🇧🇦"
			],
			[
				"name_en" => "Botswana",
				"name_es" => "Botswana",
				"name_it" => "Botswana",
				"name_br" => "Botsuana",
				"name_fr" => "Botswana",
				"alpha2Code" => "BW",
				"alpha3Code" => "BWA",
				"dialcode" => "267",
				"currenciesCode" => "BWP",
				"currenciesSymbol" => "P",
				"flag" => "🇧🇼"
			],
			[
				"name_en" => "Bouvet Island",
				"name_es" => "Isla Bouvet",
				"name_it" => "Isola Bouvet",
				"name_br" => "Ilha Bouvet",
				"name_fr" => "Île Bouvet",
				"alpha2Code" => "BV",
				"alpha3Code" => "BVT",
				"dialcode" => "",
				"currenciesCode" => "NOK",
				"currenciesSymbol" => "kr",
				"flag" => "🏳"
			],
			[
				"name_en" => "Brazil",
				"name_es" => "Brasil",
				"name_it" => "Brasile",
				"name_br" => "Brasil",
				"name_fr" => "Brésil",
				"alpha2Code" => "BR",
				"alpha3Code" => "BRA",
				"dialcode" => "55",
				"currenciesCode" => "BRL",
				"currenciesSymbol" => "R$",
				"flag" => "🇧🇷"
			],
			[
				"name_en" => "British Indian Ocean Territory",
				"name_es" => "Territorio Británico del Océano Índico",
				"name_it" => "Territorio britannico dell'oceano indiano",
				"name_br" => "Território Britânico do Oceano íÍdico",
				"name_fr" => "Territoire britannique de l'océan Indien",
				"alpha2Code" => "IO",
				"alpha3Code" => "IOT",
				"dialcode" => "246",
				"currenciesCode" => "USD",
				"currenciesSymbol" => "$",
				"flag" => "🇮🇴"
			],
			[
				"name_en" => "United States Minor Outlying Islands",
				"name_es" => "Islas Ultramarinas Menores de Estados Unidos",
				"name_it" => "Isole minori esterne degli Stati Uniti d'America",
				"name_br" => "Ilhas Menores Distantes dos Estados Unidos",
				"name_fr" => "Îles mineures éloignées des États-Unis",
				"alpha2Code" => "UM",
				"alpha3Code" => "UMI",
				"dialcode" => "",
				"currenciesCode" => "USD",
				"currenciesSymbol" => "$",
				"flag" => ""
			],
			[
				"name_en" => "Virgin Islands (British)",
				"name_es" => "Islas Vírgenes del Reino Unido",
				"name_it" => "Isole Vergini Britanniche",
				"name_br" => "Ilhas Virgens Britânicas",
				"name_fr" => "Îles Vierges britanniques",
				"alpha2Code" => "VG",
				"alpha3Code" => "VGB",
				"dialcode" => "1284",
				"currenciesCode" => "",
				"currenciesSymbol" => "$",
				"flag" => "🇻🇬"
			],
			[
				"name_en" => "Virgin Islands (U.S.)",
				"name_es" => "Islas Vírgenes de los Estados Unidos",
				"name_it" => "Isole Vergini americane",
				"name_br" => "Ilhas Virgens Americanas",
				"name_fr" => "Îles Vierges des États-Unis",
				"alpha2Code" => "VI",
				"alpha3Code" => "VIR",
				"dialcode" => "1 340",
				"currenciesCode" => "USD",
				"currenciesSymbol" => "$",
				"flag" => "🇻🇮"
			],
			[
				"name_en" => "Brunei Darussalam",
				"name_es" => "Brunei",
				"name_it" => "Brunei",
				"name_br" => "Brunei",
				"name_fr" => "Brunei",
				"alpha2Code" => "BN",
				"alpha3Code" => "BRN",
				"dialcode" => "673",
				"currenciesCode" => "BND",
				"currenciesSymbol" => "$",
				"flag" => "🇧🇳"
			],
			[
				"name_en" => "Bulgaria",
				"name_es" => "Bulgaria",
				"name_it" => "Bulgaria",
				"name_br" => "Bulgária",
				"name_fr" => "Bulgarie",
				"alpha2Code" => "BG",
				"alpha3Code" => "BGR",
				"dialcode" => "359",
				"currenciesCode" => "BGN",
				"currenciesSymbol" => "лв",
				"flag" => "🇧🇬"
			],
			[
				"name_en" => "Burkina Faso",
				"name_es" => "Burkina Faso",
				"name_it" => "Burkina Faso",
				"name_br" => "Burkina Faso",
				"name_fr" => "Burkina Faso",
				"alpha2Code" => "BF",
				"alpha3Code" => "BFA",
				"dialcode" => "226",
				"currenciesCode" => "XOF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇧🇫"
			],
			[
				"name_en" => "Burundi",
				"name_es" => "Burundi",
				"name_it" => "Burundi",
				"name_br" => "Burundi",
				"name_fr" => "Burundi",
				"alpha2Code" => "BI",
				"alpha3Code" => "BDI",
				"dialcode" => "257",
				"currenciesCode" => "BIF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇧🇮"
			],
			[
				"name_en" => "Cambodia",
				"name_es" => "Camboya",
				"name_it" => "Cambogia",
				"name_br" => "Camboja",
				"name_fr" => "Cambodge",
				"alpha2Code" => "KH",
				"alpha3Code" => "KHM",
				"dialcode" => "855",
				"currenciesCode" => "KHR",
				"currenciesSymbol" => "៛",
				"flag" => "🇰🇭"
			],
			[
				"name_en" => "Cameroon",
				"name_es" => "Camerún",
				"name_it" => "Camerun",
				"name_br" => "Camarões",
				"name_fr" => "Cameroun",
				"alpha2Code" => "CM",
				"alpha3Code" => "CMR",
				"dialcode" => "237",
				"currenciesCode" => "XAF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇨🇲"
			],
			[
				"name_en" => "Canada",
				"name_es" => "Canadá",
				"name_it" => "Canada",
				"name_br" => "Canadá",
				"name_fr" => "Canada",
				"alpha2Code" => "CA",
				"alpha3Code" => "CAN",
				"dialcode" => "1",
				"currenciesCode" => "CAD",
				"currenciesSymbol" => "$",
				"flag" => "🇨🇦"
			],
			[
				"name_en" => "Cabo Verde",
				"name_es" => "Cabo Verde",
				"name_it" => "Capo Verde",
				"name_br" => "Cabo Verde",
				"name_fr" => "Cap Vert",
				"alpha2Code" => "CV",
				"alpha3Code" => "CPV",
				"dialcode" => "238",
				"currenciesCode" => "CVE",
				"currenciesSymbol" => "Esc",
				"flag" => "🇨🇻"
			],
			[
				"name_en" => "Cayman Islands",
				"name_es" => "Islas Caimán",
				"name_it" => "Isole Cayman",
				"name_br" => "Ilhas Cayman",
				"name_fr" => "Îles Caïmans",
				"alpha2Code" => "KY",
				"alpha3Code" => "CYM",
				"dialcode" => "1345",
				"currenciesCode" => "KYD",
				"currenciesSymbol" => "$",
				"flag" => "🇰🇾"
			],
			[
				"name_en" => "Central African Republic",
				"name_es" => "República Centroafricana",
				"name_it" => "Repubblica Centrafricana",
				"name_br" => "República Centro-Africana",
				"name_fr" => "République centrafricaine",
				"alpha2Code" => "CF",
				"alpha3Code" => "CAF",
				"dialcode" => "236",
				"currenciesCode" => "XAF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇨🇫"
			],
			[
				"name_en" => "Chad",
				"name_es" => "Chad",
				"name_it" => "Ciad",
				"name_br" => "Chade",
				"name_fr" => "Tchad",
				"alpha2Code" => "TD",
				"alpha3Code" => "TCD",
				"dialcode" => "235",
				"currenciesCode" => "XAF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇹🇩"
			],
			[
				"name_en" => "Chile",
				"name_es" => "Chile",
				"name_it" => "Cile",
				"name_br" => "Chile",
				"name_fr" => "Chili",
				"alpha2Code" => "CL",
				"alpha3Code" => "CHL",
				"dialcode" => "56",
				"currenciesCode" => "CLP",
				"currenciesSymbol" => "$",
				"flag" => "🇨🇱"
			],
			[
				"name_en" => "China",
				"name_es" => "China",
				"name_it" => "Cina",
				"name_br" => "China",
				"name_fr" => "Chine",
				"alpha2Code" => "CN",
				"alpha3Code" => "CHN",
				"dialcode" => "86",
				"currenciesCode" => "CNY",
				"currenciesSymbol" => "¥",
				"flag" => "🇨🇳"
			],
			[
				"name_en" => "Christmas Island",
				"name_es" => "Isla de Navidad",
				"name_it" => "Isola di Natale",
				"name_br" => "Ilha Christmas",
				"name_fr" => "Île Christmas",
				"alpha2Code" => "CX",
				"alpha3Code" => "CXR",
				"dialcode" => "61",
				"currenciesCode" => "AUD",
				"currenciesSymbol" => "$",
				"flag" => "🇨🇽"
			],
			[
				"name_en" => "Cocos (Keeling) Islands",
				"name_es" => "Islas Cocos o Islas Keeling",
				"name_it" => "Isole Cocos e Keeling",
				"name_br" => "Ilhas Cocos",
				"name_fr" => "Îles Cocos",
				"alpha2Code" => "CC",
				"alpha3Code" => "CCK",
				"dialcode" => "61",
				"currenciesCode" => "AUD",
				"currenciesSymbol" => "$",
				"flag" => "🇨🇨"
			],
			[
				"name_en" => "Colombia",
				"name_es" => "Colombia",
				"name_it" => "Colombia",
				"name_br" => "Colômbia",
				"name_fr" => "Colombie",
				"alpha2Code" => "CO",
				"alpha3Code" => "COL",
				"dialcode" => "57",
				"currenciesCode" => "COP",
				"currenciesSymbol" => "$",
				"flag" => "🇨🇴"
			],
			[
				"name_en" => "Comoros",
				"name_es" => "Comoras",
				"name_it" => "Comore",
				"name_br" => "Comores",
				"name_fr" => "Comores",
				"alpha2Code" => "KM",
				"alpha3Code" => "COM",
				"dialcode" => "269",
				"currenciesCode" => "KMF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇰🇲"
			],
			[
				"name_en" => "Congo",
				"name_es" => "Congo",
				"name_it" => "Congo",
				"name_br" => "Congo",
				"name_fr" => "Congo",
				"alpha2Code" => "CG",
				"alpha3Code" => "COG",
				"dialcode" => "242",
				"currenciesCode" => "XAF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇨🇬"
			],
			[
				"name_en" => "Congo (Democratic Republic of the)",
				"name_es" => "Congo (Rep. Dem.)",
				"name_it" => "Congo (Rep. Dem.)",
				"name_br" => "RD Congo",
				"name_fr" => "Congo (Rép. dém.)",
				"alpha2Code" => "CD",
				"alpha3Code" => "COD",
				"dialcode" => "243",
				"currenciesCode" => "CDF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇨🇩"
			],
			[
				"name_en" => "Cook Islands",
				"name_es" => "Islas Cook",
				"name_it" => "Isole Cook",
				"name_br" => "Ilhas Cook",
				"name_fr" => "Îles Cook",
				"alpha2Code" => "CK",
				"alpha3Code" => "COK",
				"dialcode" => "682",
				"currenciesCode" => "NZD",
				"currenciesSymbol" => "$",
				"flag" => "🇨🇰"
			],
			[
				"name_en" => "Costa Rica",
				"name_es" => "Costa Rica",
				"name_it" => "Costa Rica",
				"name_br" => "Costa Rica",
				"name_fr" => "Costa Rica",
				"alpha2Code" => "CR",
				"alpha3Code" => "CRI",
				"dialcode" => "506",
				"currenciesCode" => "CRC",
				"currenciesSymbol" => "₡",
				"flag" => "🇨🇷"
			],
			[
				"name_en" => "Croatia",
				"name_es" => "Croacia",
				"name_it" => "Croazia",
				"name_br" => "Croácia",
				"name_fr" => "Croatie",
				"alpha2Code" => "HR",
				"alpha3Code" => "HRV",
				"dialcode" => "385",
				"currenciesCode" => "HRK",
				"currenciesSymbol" => "kn",
				"flag" => "🇭🇷"
			],
			[
				"name_en" => "Cuba",
				"name_es" => "Cuba",
				"name_it" => "Cuba",
				"name_br" => "Cuba",
				"name_fr" => "Cuba",
				"alpha2Code" => "CU",
				"alpha3Code" => "CUB",
				"dialcode" => "53",
				"currenciesCode" => "CUC",
				"currenciesSymbol" => "$",
				"flag" => "🇨🇺"
			],
			[
				"name_en" => "Curaçao",
				"name_es" => "Curazao",
				"name_it" => "Curaçao",
				"name_br" => "Curaçao",
				"name_fr" => "Curaçao",
				"alpha2Code" => "CW",
				"alpha3Code" => "CUW",
				"dialcode" => "599",
				"currenciesCode" => "ANG",
				"currenciesSymbol" => "ƒ",
				"flag" => ""
			],
			[
				"name_en" => "Cyprus",
				"name_es" => "Chipre",
				"name_it" => "Cipro",
				"name_br" => "Chipre",
				"name_fr" => "Chypre",
				"alpha2Code" => "CY",
				"alpha3Code" => "CYP",
				"dialcode" => "357",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇨🇾"
			],
			[
				"name_en" => "Czech Republic",
				"name_es" => "República Checa",
				"name_it" => "Repubblica Ceca",
				"name_br" => "República Tcheca",
				"name_fr" => "République tchèque",
				"alpha2Code" => "CZ",
				"alpha3Code" => "CZE",
				"dialcode" => "420",
				"currenciesCode" => "CZK",
				"currenciesSymbol" => "Kč",
				"flag" => "🇨🇿"
			],
			[
				"name_en" => "Denmark",
				"name_es" => "Dinamarca",
				"name_it" => "Danimarca",
				"name_br" => "Dinamarca",
				"name_fr" => "Danemark",
				"alpha2Code" => "DK",
				"alpha3Code" => "DNK",
				"dialcode" => "45",
				"currenciesCode" => "DKK",
				"currenciesSymbol" => "kr",
				"flag" => "🇩🇰"
			],
			[
				"name_en" => "Djibouti",
				"name_es" => "Yibuti",
				"name_it" => "Gibuti",
				"name_br" => "Djibuti",
				"name_fr" => "Djibouti",
				"alpha2Code" => "DJ",
				"alpha3Code" => "DJI",
				"dialcode" => "253",
				"currenciesCode" => "DJF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇩🇯"
			],
			[
				"name_en" => "Dominica",
				"name_es" => "Dominica",
				"name_it" => "Dominica",
				"name_br" => "Dominica",
				"name_fr" => "Dominique",
				"alpha2Code" => "DM",
				"alpha3Code" => "DMA",
				"dialcode" => "1767",
				"currenciesCode" => "XCD",
				"currenciesSymbol" => "$",
				"flag" => "🇩🇲"
			],
			[
				"name_en" => "Dominican Republic",
				"name_es" => "República Dominicana",
				"name_it" => "Repubblica Dominicana",
				"name_br" => "República Dominicana",
				"name_fr" => "République dominicaine",
				"alpha2Code" => "DO",
				"alpha3Code" => "DOM",
				"dialcode" => "1809",
				"currenciesCode" => "DOP",
				"currenciesSymbol" => "$",
				"flag" => "🇨🇩"
			],
			[
				"name_en" => "Ecuador",
				"name_es" => "Ecuador",
				"name_it" => "Ecuador",
				"name_br" => "Equador",
				"name_fr" => "Équateur",
				"alpha2Code" => "EC",
				"alpha3Code" => "ECU",
				"dialcode" => "593",
				"currenciesCode" => "USD",
				"currenciesSymbol" => "$",
				"flag" => "🇪🇨"
			],
			[
				"name_en" => "Egypt",
				"name_es" => "Egipto",
				"name_it" => "Egitto",
				"name_br" => "Egito",
				"name_fr" => "Égypte",
				"alpha2Code" => "EG",
				"alpha3Code" => "EGY",
				"dialcode" => "20",
				"currenciesCode" => "EGP",
				"currenciesSymbol" => "£",
				"flag" => "🇪🇬"
			],
			[
				"name_en" => "El Salvador",
				"name_es" => "El Salvador",
				"name_it" => "El Salvador",
				"name_br" => "El Salvador",
				"name_fr" => "Salvador",
				"alpha2Code" => "SV",
				"alpha3Code" => "SLV",
				"dialcode" => "503",
				"currenciesCode" => "USD",
				"currenciesSymbol" => "$",
				"flag" => "🇸🇻"
			],
			[
				"name_en" => "Equatorial Guinea",
				"name_es" => "Guinea Ecuatorial",
				"name_it" => "Guinea Equatoriale",
				"name_br" => "Guiné Equatorial",
				"name_fr" => "Guinée-Équatoriale",
				"alpha2Code" => "GQ",
				"alpha3Code" => "GNQ",
				"dialcode" => "240",
				"currenciesCode" => "XAF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇬🇶"
			],
			[
				"name_en" => "Eritrea",
				"name_es" => "Eritrea",
				"name_it" => "Eritrea",
				"name_br" => "Eritreia",
				"name_fr" => "Érythrée",
				"alpha2Code" => "ER",
				"alpha3Code" => "ERI",
				"dialcode" => "291",
				"currenciesCode" => "ERN",
				"currenciesSymbol" => "Nfk",
				"flag" => "🇪🇷"
			],
			[
				"name_en" => "Estonia",
				"name_es" => "Estonia",
				"name_it" => "Estonia",
				"name_br" => "Estônia",
				"name_fr" => "Estonie",
				"alpha2Code" => "EE",
				"alpha3Code" => "EST",
				"dialcode" => "372",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇪🇪"
			],
			[
				"name_en" => "Ethiopia",
				"name_es" => "Etiopía",
				"name_it" => "Etiopia",
				"name_br" => "Etiópia",
				"name_fr" => "Éthiopie",
				"alpha2Code" => "ET",
				"alpha3Code" => "ETH",
				"dialcode" => "251",
				"currenciesCode" => "ETB",
				"currenciesSymbol" => "Br",
				"flag" => "🇪🇹"
			],
			[
				"name_en" => "Falkland Islands (Malvinas)",
				"name_es" => "Islas Malvinas",
				"name_it" => "Isole Falkland o Isole Malvine",
				"name_br" => "Ilhas Malvinas",
				"name_fr" => "Îles Malouines",
				"alpha2Code" => "FK",
				"alpha3Code" => "FLK",
				"dialcode" => "500",
				"currenciesCode" => "FKP",
				"currenciesSymbol" => "£",
				"flag" => "🇫🇰"
			],
			[
				"name_en" => "Faroe Islands",
				"name_es" => "Islas Faroe",
				"name_it" => "Isole Far Oer",
				"name_br" => "Ilhas Faroé",
				"name_fr" => "Îles Féroé",
				"alpha2Code" => "FO",
				"alpha3Code" => "FRO",
				"dialcode" => "298",
				"currenciesCode" => "DKK",
				"currenciesSymbol" => "kr",
				"flag" => "🇫🇴"
			],
			[
				"name_en" => "Fiji",
				"name_es" => "Fiyi",
				"name_it" => "Figi",
				"name_br" => "Fiji",
				"name_fr" => "Fidji",
				"alpha2Code" => "FJ",
				"alpha3Code" => "FJI",
				"dialcode" => "679",
				"currenciesCode" => "FJD",
				"currenciesSymbol" => "$",
				"flag" => "🇫🇯"
			],
			[
				"name_en" => "Finland",
				"name_es" => "Finlandia",
				"name_it" => "Finlandia",
				"name_br" => "Finlândia",
				"name_fr" => "Finlande",
				"alpha2Code" => "FI",
				"alpha3Code" => "FIN",
				"dialcode" => "358",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇫🇮"
			],
			[
				"name_en" => "France",
				"name_es" => "Francia",
				"name_it" => "Francia",
				"name_br" => "França",
				"name_fr" => "France",
				"alpha2Code" => "FR",
				"alpha3Code" => "FRA",
				"dialcode" => "33",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇫🇷"
			],
			[
				"name_en" => "French Guiana",
				"name_es" => "Guayana Francesa",
				"name_it" => "Guyana francese",
				"name_br" => "Guiana Francesa",
				"name_fr" => "Guayane",
				"alpha2Code" => "GF",
				"alpha3Code" => "GUF",
				"dialcode" => "594",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇬🇫"
			],
			[
				"name_en" => "French Polynesia",
				"name_es" => "Polinesia Francesa",
				"name_it" => "Polinesia Francese",
				"name_br" => "Polinésia Francesa",
				"name_fr" => "Polynésie française",
				"alpha2Code" => "PF",
				"alpha3Code" => "PYF",
				"dialcode" => "689",
				"currenciesCode" => "XPF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇵🇫"
			],
			[
				"name_en" => "French Southern Territories",
				"name_es" => "Tierras Australes y Antárticas Francesas",
				"name_it" => "Territori Francesi del Sud",
				"name_br" => "Terras Austrais e Antárticas Francesas",
				"name_fr" => "Terres australes et antarctiques françaises",
				"alpha2Code" => "TF",
				"alpha3Code" => "ATF",
				"dialcode" => "",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇹🇫"
			],
			[
				"name_en" => "Gabon",
				"name_es" => "Gabón",
				"name_it" => "Gabon",
				"name_br" => "Gabão",
				"name_fr" => "Gabon",
				"alpha2Code" => "GA",
				"alpha3Code" => "GAB",
				"dialcode" => "241",
				"currenciesCode" => "XAF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇬🇦"
			],
			[
				"name_en" => "Gambia",
				"name_es" => "Gambia",
				"name_it" => "Gambia",
				"name_br" => "Gâmbia",
				"name_fr" => "Gambie",
				"alpha2Code" => "GM",
				"alpha3Code" => "GMB",
				"dialcode" => "220",
				"currenciesCode" => "GMD",
				"currenciesSymbol" => "D",
				"flag" => "🇬🇲"
			],
			[
				"name_en" => "Georgia",
				"name_es" => "Georgia",
				"name_it" => "Georgia",
				"name_br" => "Geórgia",
				"name_fr" => "Géorgie",
				"alpha2Code" => "GE",
				"alpha3Code" => "GEO",
				"dialcode" => "995",
				"currenciesCode" => "GEL",
				"currenciesSymbol" => "ლ",
				"flag" => "🇬🇪"
			],
			[
				"name_en" => "Germany",
				"name_es" => "Alemania",
				"name_it" => "Germania",
				"name_br" => "Alemanha",
				"name_fr" => "Allemagne",
				"alpha2Code" => "DE",
				"alpha3Code" => "DEU",
				"dialcode" => "49",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇩🇪"
			],
			[
				"name_en" => "Ghana",
				"name_es" => "Ghana",
				"name_it" => "Ghana",
				"name_br" => "Gana",
				"name_fr" => "Ghana",
				"alpha2Code" => "GH",
				"alpha3Code" => "GHA",
				"dialcode" => "233",
				"currenciesCode" => "GHS",
				"currenciesSymbol" => "₵",
				"flag" => "🇬🇭"
			],
			[
				"name_en" => "Gibraltar",
				"name_es" => "Gibraltar",
				"name_it" => "Gibilterra",
				"name_br" => "Gibraltar",
				"name_fr" => "Gibraltar",
				"alpha2Code" => "GI",
				"alpha3Code" => "GIB",
				"dialcode" => "350",
				"currenciesCode" => "GIP",
				"currenciesSymbol" => "£",
				"flag" => "🇬🇮"
			],
			[
				"name_en" => "Greece",
				"name_es" => "Grecia",
				"name_it" => "Grecia",
				"name_br" => "Grécia",
				"name_fr" => "Grèce",
				"alpha2Code" => "GR",
				"alpha3Code" => "GRC",
				"dialcode" => "30",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇬🇷"
			],
			[
				"name_en" => "Greenland",
				"name_es" => "Groenlandia",
				"name_it" => "Groenlandia",
				"name_br" => "Groelândia",
				"name_fr" => "Groenland",
				"alpha2Code" => "GL",
				"alpha3Code" => "GRL",
				"dialcode" => "299",
				"currenciesCode" => "DKK",
				"currenciesSymbol" => "kr",
				"flag" => "🇬🇱"
			],
			[
				"name_en" => "Grenada",
				"name_es" => "Grenada",
				"name_it" => "Grenada",
				"name_br" => "Granada",
				"name_fr" => "Grenade",
				"alpha2Code" => "GD",
				"alpha3Code" => "GRD",
				"dialcode" => "1473",
				"currenciesCode" => "XCD",
				"currenciesSymbol" => "$",
				"flag" => "🇬🇩"
			],
			[
				"name_en" => "Guadeloupe",
				"name_es" => "Guadalupe",
				"name_it" => "Guadeloupa",
				"name_br" => "Guadalupe",
				"name_fr" => "Guadeloupe",
				"alpha2Code" => "GP",
				"alpha3Code" => "GLP",
				"dialcode" => "590",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇬🇵"
			],
			[
				"name_en" => "Guam",
				"name_es" => "Guam",
				"name_it" => "Guam",
				"name_br" => "Guam",
				"name_fr" => "Guam",
				"alpha2Code" => "GU",
				"alpha3Code" => "GUM",
				"dialcode" => "1671",
				"currenciesCode" => "USD",
				"currenciesSymbol" => "$",
				"flag" => "🇬🇺"
			],
			[
				"name_en" => "Guatemala",
				"name_es" => "Guatemala",
				"name_it" => "Guatemala",
				"name_br" => "Guatemala",
				"name_fr" => "Guatemala",
				"alpha2Code" => "GT",
				"alpha3Code" => "GTM",
				"dialcode" => "502",
				"currenciesCode" => "GTQ",
				"currenciesSymbol" => "Q",
				"flag" => "🇬🇹"
			],
			[
				"name_en" => "Guernsey",
				"name_es" => "Guernsey",
				"name_it" => "Guernsey",
				"name_br" => "Guernsey",
				"name_fr" => "Guernesey",
				"alpha2Code" => "GG",
				"alpha3Code" => "GGY",
				"dialcode" => "44",
				"currenciesCode" => "GBP",
				"currenciesSymbol" => "£",
				"flag" => "🇬🇬"
			],
			[
				"name_en" => "Guinea",
				"name_es" => "Guinea",
				"name_it" => "Guinea",
				"name_br" => "Guiné",
				"name_fr" => "Guinée",
				"alpha2Code" => "GN",
				"alpha3Code" => "GIN",
				"dialcode" => "224",
				"currenciesCode" => "GNF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇬🇳"
			],
			[
				"name_en" => "Guinea-Bissau",
				"name_es" => "Guinea-Bisáu",
				"name_it" => "Guinea-Bissau",
				"name_br" => "Guiné-Bissau",
				"name_fr" => "Guinée-Bissau",
				"alpha2Code" => "GW",
				"alpha3Code" => "GNB",
				"dialcode" => "245",
				"currenciesCode" => "XOF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇬🇼"
			],
			[
				"name_en" => "Guyana",
				"name_es" => "Guyana",
				"name_it" => "Guyana",
				"name_br" => "Guiana",
				"name_fr" => "Guyane",
				"alpha2Code" => "GY",
				"alpha3Code" => "GUY",
				"dialcode" => "592",
				"currenciesCode" => "GYD",
				"currenciesSymbol" => "$",
				"flag" => "🇬🇾"
			],
			[
				"name_en" => "Haiti",
				"name_es" => "Haiti",
				"name_it" => "Haiti",
				"name_br" => "Haiti",
				"name_fr" => "Haïti",
				"alpha2Code" => "HT",
				"alpha3Code" => "HTI",
				"dialcode" => "509",
				"currenciesCode" => "HTG",
				"currenciesSymbol" => "G",
				"flag" => "🇭🇹"
			],
			[
				"name_en" => "Heard Island and McDonald Islands",
				"name_es" => "Islas Heard y McDonald",
				"name_it" => "Isole Heard e McDonald",
				"name_br" => "Ilha Heard e Ilhas McDonald",
				"name_fr" => "Îles Heard-et-MacDonald",
				"alpha2Code" => "HM",
				"alpha3Code" => "HMD",
				"dialcode" => "",
				"currenciesCode" => "AUD",
				"currenciesSymbol" => "$",
				"flag" => "🏳"
			],
			[
				"name_en" => "Holy See",
				"name_es" => "Santa Sede",
				"name_it" => "Santa Sede",
				"name_br" => "Vaticano",
				"name_fr" => "voir Saint",
				"alpha2Code" => "VA",
				"alpha3Code" => "VAT",
				"dialcode" => "379",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇻🇦"
			],
			[
				"name_en" => "Honduras",
				"name_es" => "Honduras",
				"name_it" => "Honduras",
				"name_br" => "Honduras",
				"name_fr" => "Honduras",
				"alpha2Code" => "HN",
				"alpha3Code" => "HND",
				"dialcode" => "504",
				"currenciesCode" => "HNL",
				"currenciesSymbol" => "L",
				"flag" => "🇭🇳"
			],
			[
				"name_en" => "Hong Kong",
				"name_es" => "Hong Kong",
				"name_it" => "Hong Kong",
				"name_br" => "Hong Kong",
				"name_fr" => "Hong Kong",
				"alpha2Code" => "HK",
				"alpha3Code" => "HKG",
				"dialcode" => "852",
				"currenciesCode" => "HKD",
				"currenciesSymbol" => "$",
				"flag" => "🇭🇰"
			],
			[
				"name_en" => "Hungary",
				"name_es" => "Hungría",
				"name_it" => "Ungheria",
				"name_br" => "Hungria",
				"name_fr" => "Hongrie",
				"alpha2Code" => "HU",
				"alpha3Code" => "HUN",
				"dialcode" => "36",
				"currenciesCode" => "HUF",
				"currenciesSymbol" => "Ft",
				"flag" => "🇭🇺"
			],
			[
				"name_en" => "Iceland",
				"name_es" => "Islandia",
				"name_it" => "Islanda",
				"name_br" => "Islândia",
				"name_fr" => "Islande",
				"alpha2Code" => "IS",
				"alpha3Code" => "ISL",
				"dialcode" => "354",
				"currenciesCode" => "ISK",
				"currenciesSymbol" => "kr",
				"flag" => "🇮🇸"
			],
			[
				"name_en" => "India",
				"name_es" => "India",
				"name_it" => "India",
				"name_br" => "Índia",
				"name_fr" => "Inde",
				"alpha2Code" => "IN",
				"alpha3Code" => "IND",
				"dialcode" => "91",
				"currenciesCode" => "INR",
				"currenciesSymbol" => "₹",
				"flag" => "🇮🇳"
			],
			[
				"name_en" => "Indonesia",
				"name_es" => "Indonesia",
				"name_it" => "Indonesia",
				"name_br" => "Indonésia",
				"name_fr" => "Indonésie",
				"alpha2Code" => "ID",
				"alpha3Code" => "IDN",
				"dialcode" => "62",
				"currenciesCode" => "IDR",
				"currenciesSymbol" => "Rp",
				"flag" => "🇮🇩"
			],
			[
				"name_en" => "Côte d'Ivoire",
				"name_es" => "Costa de Marfil",
				"name_it" => "Costa D'Avorio",
				"name_br" => "Costa do Marfim",
				"name_fr" => "Côte d'Ivoire",
				"alpha2Code" => "CI",
				"alpha3Code" => "CIV",
				"dialcode" => "225",
				"currenciesCode" => "XOF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇨🇮"
			],
			[
				"name_en" => "Iran (Islamic Republic of)",
				"name_es" => "Iran",
				"name_it" => "",
				"name_br" => "Irã",
				"name_fr" => "Iran",
				"alpha2Code" => "IR",
				"alpha3Code" => "IRN",
				"dialcode" => "98",
				"currenciesCode" => "IRR",
				"currenciesSymbol" => "﷼",
				"flag" => "🇮🇷"
			],
			[
				"name_en" => "Iraq",
				"name_es" => "Irak",
				"name_it" => "Iraq",
				"name_br" => "Iraque",
				"name_fr" => "Irak",
				"alpha2Code" => "IQ",
				"alpha3Code" => "IRQ",
				"dialcode" => "964",
				"currenciesCode" => "IQD",
				"currenciesSymbol" => "ع.د",
				"flag" => "🇮🇶"
			],
			[
				"name_en" => "Ireland",
				"name_es" => "Irlanda",
				"name_it" => "Irlanda",
				"name_br" => "Irlanda",
				"name_fr" => "Irlande",
				"alpha2Code" => "IE",
				"alpha3Code" => "IRL",
				"dialcode" => "353",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇮🇪"
			],
			[
				"name_en" => "Isle of Man",
				"name_es" => "Isla de Man",
				"name_it" => "Isola di Man",
				"name_br" => "Ilha de Man",
				"name_fr" => "Île de Man",
				"alpha2Code" => "IM",
				"alpha3Code" => "IMN",
				"dialcode" => "44",
				"currenciesCode" => "GBP",
				"currenciesSymbol" => "£",
				"flag" => "🇮🇲"
			],
			[
				"name_en" => "Israel",
				"name_es" => "Israel",
				"name_it" => "Israele",
				"name_br" => "Israel",
				"name_fr" => "Israël",
				"alpha2Code" => "IL",
				"alpha3Code" => "ISR",
				"dialcode" => "972",
				"currenciesCode" => "ILS",
				"currenciesSymbol" => "₪",
				"flag" => "🇮🇱"
			],
			[
				"name_en" => "Italy",
				"name_es" => "Italia",
				"name_it" => "Italia",
				"name_br" => "Itália",
				"name_fr" => "Italie",
				"alpha2Code" => "IT",
				"alpha3Code" => "ITA",
				"dialcode" => "39",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇮🇹"
			],
			[
				"name_en" => "Jamaica",
				"name_es" => "Jamaica",
				"name_it" => "Giamaica",
				"name_br" => "Jamaica",
				"name_fr" => "Jamaïque",
				"alpha2Code" => "JM",
				"alpha3Code" => "JAM",
				"dialcode" => "1876",
				"currenciesCode" => "JMD",
				"currenciesSymbol" => "$",
				"flag" => "🇯🇲"
			],
			[
				"name_en" => "Japan",
				"name_es" => "Japón",
				"name_it" => "Giappone",
				"name_br" => "Japão",
				"name_fr" => "Japon",
				"alpha2Code" => "JP",
				"alpha3Code" => "JPN",
				"dialcode" => "81",
				"currenciesCode" => "JPY",
				"currenciesSymbol" => "¥",
				"flag" => "🇯🇵"
			],
			[
				"name_en" => "Jersey",
				"name_es" => "Jersey",
				"name_it" => "Isola di Jersey",
				"name_br" => "Jersey",
				"name_fr" => "Jersey",
				"alpha2Code" => "JE",
				"alpha3Code" => "JEY",
				"dialcode" => "44",
				"currenciesCode" => "GBP",
				"currenciesSymbol" => "£",
				"flag" => "🇯🇪"
			],
			[
				"name_en" => "Jordan",
				"name_es" => "Jordania",
				"name_it" => "Giordania",
				"name_br" => "Jordânia",
				"name_fr" => "Jordanie",
				"alpha2Code" => "JO",
				"alpha3Code" => "JOR",
				"dialcode" => "962",
				"currenciesCode" => "JOD",
				"currenciesSymbol" => "د.ا",
				"flag" => "🇯🇴"
			],
			[
				"name_en" => "Kazakhstan",
				"name_es" => "Kazajistán",
				"name_it" => "Kazakistan",
				"name_br" => "Cazaquistão",
				"name_fr" => "Kazakhstan",
				"alpha2Code" => "KZ",
				"alpha3Code" => "KAZ",
				"dialcode" => "76",
				"currenciesCode" => "KZT",
				"currenciesSymbol" => "",
				"flag" => "🇰🇿"
			],
			[
				"name_en" => "Kenya",
				"name_es" => "Kenia",
				"name_it" => "Kenya",
				"name_br" => "Quênia",
				"name_fr" => "Kenya",
				"alpha2Code" => "KE",
				"alpha3Code" => "KEN",
				"dialcode" => "254",
				"currenciesCode" => "KES",
				"currenciesSymbol" => "Sh",
				"flag" => "🇰🇪"
			],
			[
				"name_en" => "Kiribati",
				"name_es" => "Kiribati",
				"name_it" => "Kiribati",
				"name_br" => "Kiribati",
				"name_fr" => "Kiribati",
				"alpha2Code" => "KI",
				"alpha3Code" => "KIR",
				"dialcode" => "686",
				"currenciesCode" => "AUD",
				"currenciesSymbol" => "$",
				"flag" => "🇰🇮"
			],
			[
				"name_en" => "Kuwait",
				"name_es" => "Kuwait",
				"name_it" => "Kuwait",
				"name_br" => "Kuwait",
				"name_fr" => "Koweït",
				"alpha2Code" => "KW",
				"alpha3Code" => "KWT",
				"dialcode" => "965",
				"currenciesCode" => "KWD",
				"currenciesSymbol" => "د.ك",
				"flag" => "🇰🇼"
			],
			[
				"name_en" => "Kyrgyzstan",
				"name_es" => "Kirguizistán",
				"name_it" => "Kirghizistan",
				"name_br" => "Quirguistão",
				"name_fr" => "Kirghizistan",
				"alpha2Code" => "KG",
				"alpha3Code" => "KGZ",
				"dialcode" => "996",
				"currenciesCode" => "KGS",
				"currenciesSymbol" => "с",
				"flag" => "🇰🇬"
			],
			[
				"name_en" => "Lao People's Democratic Republic",
				"name_es" => "Laos",
				"name_it" => "Laos",
				"name_br" => "Laos",
				"name_fr" => "Laos",
				"alpha2Code" => "LA",
				"alpha3Code" => "LAO",
				"dialcode" => "856",
				"currenciesCode" => "LAK",
				"currenciesSymbol" => "₭",
				"flag" => "🇱🇦"
			],
			[
				"name_en" => "Latvia",
				"name_es" => "Letonia",
				"name_it" => "Lettonia",
				"name_br" => "Letônia",
				"name_fr" => "Lettonie",
				"alpha2Code" => "LV",
				"alpha3Code" => "LVA",
				"dialcode" => "371",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇱🇻"
			],
			[
				"name_en" => "Lebanon",
				"name_es" => "Líbano",
				"name_it" => "Libano",
				"name_br" => "Líbano",
				"name_fr" => "Liban",
				"alpha2Code" => "LB",
				"alpha3Code" => "LBN",
				"dialcode" => "961",
				"currenciesCode" => "LBP",
				"currenciesSymbol" => "ل.ل",
				"flag" => "🇱🇧"
			],
			[
				"name_en" => "Lesotho",
				"name_es" => "Lesotho",
				"name_it" => "Lesotho",
				"name_br" => "Lesoto",
				"name_fr" => "Lesotho",
				"alpha2Code" => "LS",
				"alpha3Code" => "LSO",
				"dialcode" => "266",
				"currenciesCode" => "LSL",
				"currenciesSymbol" => "L",
				"flag" => "🇱🇸"
			],
			[
				"name_en" => "Liberia",
				"name_es" => "Liberia",
				"name_it" => "Liberia",
				"name_br" => "Libéria",
				"name_fr" => "Liberia",
				"alpha2Code" => "LR",
				"alpha3Code" => "LBR",
				"dialcode" => "231",
				"currenciesCode" => "LRD",
				"currenciesSymbol" => "$",
				"flag" => "🇱🇷"
			],
			[
				"name_en" => "Libya",
				"name_es" => "Libia",
				"name_it" => "Libia",
				"name_br" => "Líbia",
				"name_fr" => "Libye",
				"alpha2Code" => "LY",
				"alpha3Code" => "LBY",
				"dialcode" => "218",
				"currenciesCode" => "LYD",
				"currenciesSymbol" => "ل.د",
				"flag" => "🇱🇾"
			],
			[
				"name_en" => "Liechtenstein",
				"name_es" => "Liechtenstein",
				"name_it" => "Liechtenstein",
				"name_br" => "Liechtenstein",
				"name_fr" => "Liechtenstein",
				"alpha2Code" => "LI",
				"alpha3Code" => "LIE",
				"dialcode" => "423",
				"currenciesCode" => "CHF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇱🇮"
			],
			[
				"name_en" => "Lithuania",
				"name_es" => "Lituania",
				"name_it" => "Lituania",
				"name_br" => "Lituânia",
				"name_fr" => "Lituanie",
				"alpha2Code" => "LT",
				"alpha3Code" => "LTU",
				"dialcode" => "370",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇱🇹"
			],
			[
				"name_en" => "Luxembourg",
				"name_es" => "Luxemburgo",
				"name_it" => "Lussemburgo",
				"name_br" => "Luxemburgo",
				"name_fr" => "Luxembourg",
				"alpha2Code" => "LU",
				"alpha3Code" => "LUX",
				"dialcode" => "352",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇱🇺"
			],
			[
				"name_en" => "Macao",
				"name_es" => "Macao",
				"name_it" => "Macao",
				"name_br" => "Macau",
				"name_fr" => "Macao",
				"alpha2Code" => "MO",
				"alpha3Code" => "MAC",
				"dialcode" => "853",
				"currenciesCode" => "MOP",
				"currenciesSymbol" => "P",
				"flag" => "🇲🇴"
			],
			[
				"name_en" => "Macedonia (the former Yugoslav Republic of)",
				"name_es" => "Macedonia",
				"name_it" => "Macedonia",
				"name_br" => "Macedônia",
				"name_fr" => "Macédoine",
				"alpha2Code" => "MK",
				"alpha3Code" => "MKD",
				"dialcode" => "389",
				"currenciesCode" => "MKD",
				"currenciesSymbol" => "ден",
				"flag" => "🇲🇰"
			],
			[
				"name_en" => "Madagascar",
				"name_es" => "Madagascar",
				"name_it" => "Madagascar",
				"name_br" => "Madagascar",
				"name_fr" => "Madagascar",
				"alpha2Code" => "MG",
				"alpha3Code" => "MDG",
				"dialcode" => "261",
				"currenciesCode" => "MGA",
				"currenciesSymbol" => "Ar",
				"flag" => "🇲🇬"
			],
			[
				"name_en" => "Malawi",
				"name_es" => "Malawi",
				"name_it" => "Malawi",
				"name_br" => "Malawi",
				"name_fr" => "Malawi",
				"alpha2Code" => "MW",
				"alpha3Code" => "MWI",
				"dialcode" => "265",
				"currenciesCode" => "MWK",
				"currenciesSymbol" => "MK",
				"flag" => "🇲🇼"
			],
			[
				"name_en" => "Malaysia",
				"name_es" => "Malasia",
				"name_it" => "Malesia",
				"name_br" => "Malásia",
				"name_fr" => "Malaisie",
				"alpha2Code" => "MY",
				"alpha3Code" => "MYS",
				"dialcode" => "60",
				"currenciesCode" => "MYR",
				"currenciesSymbol" => "RM",
				"flag" => "🇲🇾"
			],
			[
				"name_en" => "Maldives",
				"name_es" => "Maldivas",
				"name_it" => "Maldive",
				"name_br" => "Maldivas",
				"name_fr" => "Maldives",
				"alpha2Code" => "MV",
				"alpha3Code" => "MDV",
				"dialcode" => "960",
				"currenciesCode" => "MVR",
				"currenciesSymbol" => ".ރ",
				"flag" => "🇲🇻"
			],
			[
				"name_en" => "Mali",
				"name_es" => "Mali",
				"name_it" => "Mali",
				"name_br" => "Mali",
				"name_fr" => "Mali",
				"alpha2Code" => "ML",
				"alpha3Code" => "MLI",
				"dialcode" => "223",
				"currenciesCode" => "XOF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇲🇱"
			],
			[
				"name_en" => "Malta",
				"name_es" => "Malta",
				"name_it" => "Malta",
				"name_br" => "Malta",
				"name_fr" => "Malte",
				"alpha2Code" => "MT",
				"alpha3Code" => "MLT",
				"dialcode" => "356",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇲🇹"
			],
			[
				"name_en" => "Marshall Islands",
				"name_es" => "Islas Marshall",
				"name_it" => "Isole Marshall",
				"name_br" => "Ilhas Marshall",
				"name_fr" => "Îles Marshall",
				"alpha2Code" => "MH",
				"alpha3Code" => "MHL",
				"dialcode" => "692",
				"currenciesCode" => "USD",
				"currenciesSymbol" => "$",
				"flag" => "🇲🇭"
			],
			[
				"name_en" => "Martinique",
				"name_es" => "Martinica",
				"name_it" => "Martinica",
				"name_br" => "Martinica",
				"name_fr" => "Martinique",
				"alpha2Code" => "MQ",
				"alpha3Code" => "MTQ",
				"dialcode" => "596",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇲🇶"
			],
			[
				"name_en" => "Mauritania",
				"name_es" => "Mauritania",
				"name_it" => "Mauritania",
				"name_br" => "Mauritânia",
				"name_fr" => "Mauritanie",
				"alpha2Code" => "MR",
				"alpha3Code" => "MRT",
				"dialcode" => "222",
				"currenciesCode" => "MRO",
				"currenciesSymbol" => "UM",
				"flag" => "🇲🇷"
			],
			[
				"name_en" => "Mauritius",
				"name_es" => "Mauricio",
				"name_it" => "Mauritius",
				"name_br" => "Maurício",
				"name_fr" => "Île Maurice",
				"alpha2Code" => "MU",
				"alpha3Code" => "MUS",
				"dialcode" => "230",
				"currenciesCode" => "MUR",
				"currenciesSymbol" => "₨",
				"flag" => "🇲🇺"
			],
			[
				"name_en" => "Mayotte",
				"name_es" => "Mayotte",
				"name_it" => "Mayotte",
				"name_br" => "Mayotte",
				"name_fr" => "Mayotte",
				"alpha2Code" => "YT",
				"alpha3Code" => "MYT",
				"dialcode" => "262",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇾🇹"
			],
			[
				"name_en" => "Mexico",
				"name_es" => "México",
				"name_it" => "Messico",
				"name_br" => "México",
				"name_fr" => "Mexique",
				"alpha2Code" => "MX",
				"alpha3Code" => "MEX",
				"dialcode" => "52",
				"currenciesCode" => "MXN",
				"currenciesSymbol" => "$",
				"flag" => "🇲🇽"
			],
			[
				"name_en" => "Micronesia (Federated States of)",
				"name_es" => "Micronesia",
				"name_it" => "Micronesia",
				"name_br" => "Micronésia",
				"name_fr" => "Micronésie",
				"alpha2Code" => "FM",
				"alpha3Code" => "FSM",
				"dialcode" => "691",
				"currenciesCode" => "",
				"currenciesSymbol" => "$",
				"flag" => "🇫🇲"
			],
			[
				"name_en" => "Moldova (Republic of)",
				"name_es" => "Moldavia",
				"name_it" => "Moldavia",
				"name_br" => "Moldávia",
				"name_fr" => "Moldavie",
				"alpha2Code" => "MD",
				"alpha3Code" => "MDA",
				"dialcode" => "373",
				"currenciesCode" => "MDL",
				"currenciesSymbol" => "L",
				"flag" => "🇲🇩"
			],
			[
				"name_en" => "Monaco",
				"name_es" => "Mónaco",
				"name_it" => "Principato di Monaco",
				"name_br" => "Mônaco",
				"name_fr" => "Monaco",
				"alpha2Code" => "MC",
				"alpha3Code" => "MCO",
				"dialcode" => "377",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇲🇨"
			],
			[
				"name_en" => "Mongolia",
				"name_es" => "Mongolia",
				"name_it" => "Mongolia",
				"name_br" => "Mongólia",
				"name_fr" => "Mongolie",
				"alpha2Code" => "MN",
				"alpha3Code" => "MNG",
				"dialcode" => "976",
				"currenciesCode" => "MNT",
				"currenciesSymbol" => "₮",
				"flag" => "🇲🇳"
			],
			[
				"name_en" => "Montenegro",
				"name_es" => "Montenegro",
				"name_it" => "Montenegro",
				"name_br" => "Montenegro",
				"name_fr" => "Monténégro",
				"alpha2Code" => "ME",
				"alpha3Code" => "MNE",
				"dialcode" => "382",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇲🇪"
			],
			[
				"name_en" => "Montserrat",
				"name_es" => "Montserrat",
				"name_it" => "Montserrat",
				"name_br" => "Montserrat",
				"name_fr" => "Montserrat",
				"alpha2Code" => "MS",
				"alpha3Code" => "MSR",
				"dialcode" => "1664",
				"currenciesCode" => "XCD",
				"currenciesSymbol" => "$",
				"flag" => "🇲🇸"
			],
			[
				"name_en" => "Morocco",
				"name_es" => "Marruecos",
				"name_it" => "Marocco",
				"name_br" => "Marrocos",
				"name_fr" => "Maroc",
				"alpha2Code" => "MA",
				"alpha3Code" => "MAR",
				"dialcode" => "212",
				"currenciesCode" => "MAD",
				"currenciesSymbol" => "د.م.",
				"flag" => "🇲🇦"
			],
			[
				"name_en" => "Mozambique",
				"name_es" => "Mozambique",
				"name_it" => "Mozambico",
				"name_br" => "Moçambique",
				"name_fr" => "Mozambique",
				"alpha2Code" => "MZ",
				"alpha3Code" => "MOZ",
				"dialcode" => "258",
				"currenciesCode" => "MZN",
				"currenciesSymbol" => "MT",
				"flag" => "🇲🇿"
			],
			[
				"name_en" => "Myanmar",
				"name_es" => "Myanmar",
				"name_it" => "Birmania",
				"name_br" => "Myanmar",
				"name_fr" => "Myanmar",
				"alpha2Code" => "MM",
				"alpha3Code" => "MMR",
				"dialcode" => "95",
				"currenciesCode" => "MMK",
				"currenciesSymbol" => "Ks",
				"flag" => "🇲🇲"
			],
			[
				"name_en" => "Namibia",
				"name_es" => "Namibia",
				"name_it" => "Namibia",
				"name_br" => "Namíbia",
				"name_fr" => "Namibie",
				"alpha2Code" => "NA",
				"alpha3Code" => "NAM",
				"dialcode" => "264",
				"currenciesCode" => "NAD",
				"currenciesSymbol" => "$",
				"flag" => "🇳🇦"
			],
			[
				"name_en" => "Nauru",
				"name_es" => "Nauru",
				"name_it" => "Nauru",
				"name_br" => "Nauru",
				"name_fr" => "Nauru",
				"alpha2Code" => "NR",
				"alpha3Code" => "NRU",
				"dialcode" => "674",
				"currenciesCode" => "AUD",
				"currenciesSymbol" => "$",
				"flag" => "🇳🇷"
			],
			[
				"name_en" => "Nepal",
				"name_es" => "Nepal",
				"name_it" => "Nepal",
				"name_br" => "Nepal",
				"name_fr" => "Népal",
				"alpha2Code" => "NP",
				"alpha3Code" => "NPL",
				"dialcode" => "977",
				"currenciesCode" => "NPR",
				"currenciesSymbol" => "₨",
				"flag" => "🇳🇵"
			],
			[
				"name_en" => "Netherlands",
				"name_es" => "Países Bajos",
				"name_it" => "Paesi Bassi",
				"name_br" => "Holanda",
				"name_fr" => "Pays-Bas",
				"alpha2Code" => "NL",
				"alpha3Code" => "NLD",
				"dialcode" => "31",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇳🇱"
			],
			[
				"name_en" => "New Caledonia",
				"name_es" => "Nueva Caledonia",
				"name_it" => "Nuova Caledonia",
				"name_br" => "Nova Caledônia",
				"name_fr" => "Nouvelle-Calédonie",
				"alpha2Code" => "NC",
				"alpha3Code" => "NCL",
				"dialcode" => "687",
				"currenciesCode" => "XPF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇳🇨"
			],
			[
				"name_en" => "New Zealand",
				"name_es" => "Nueva Zelanda",
				"name_it" => "Nuova Zelanda",
				"name_br" => "Nova Zelândia",
				"name_fr" => "Nouvelle-Zélande",
				"alpha2Code" => "NZ",
				"alpha3Code" => "NZL",
				"dialcode" => "64",
				"currenciesCode" => "NZD",
				"currenciesSymbol" => "$",
				"flag" => "🇳🇿"
			],
			[
				"name_en" => "Nicaragua",
				"name_es" => "Nicaragua",
				"name_it" => "Nicaragua",
				"name_br" => "Nicarágua",
				"name_fr" => "Nicaragua",
				"alpha2Code" => "NI",
				"alpha3Code" => "NIC",
				"dialcode" => "505",
				"currenciesCode" => "NIO",
				"currenciesSymbol" => "C$",
				"flag" => "🇳🇮"
			],
			[
				"name_en" => "Niger",
				"name_es" => "Níger",
				"name_it" => "Niger",
				"name_br" => "Níger",
				"name_fr" => "Niger",
				"alpha2Code" => "NE",
				"alpha3Code" => "NER",
				"dialcode" => "227",
				"currenciesCode" => "XOF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇳🇪"
			],
			[
				"name_en" => "Nigeria",
				"name_es" => "Nigeria",
				"name_it" => "Nigeria",
				"name_br" => "Nigéria",
				"name_fr" => "Nigéria",
				"alpha2Code" => "NG",
				"alpha3Code" => "NGA",
				"dialcode" => "234",
				"currenciesCode" => "NGN",
				"currenciesSymbol" => "₦",
				"flag" => "🇳🇬"
			],
			[
				"name_en" => "Niue",
				"name_es" => "Niue",
				"name_it" => "Niue",
				"name_br" => "Niue",
				"name_fr" => "Niue",
				"alpha2Code" => "NU",
				"alpha3Code" => "NIU",
				"dialcode" => "683",
				"currenciesCode" => "NZD",
				"currenciesSymbol" => "$",
				"flag" => "🇳🇺"
			],
			[
				"name_en" => "Norfolk Island",
				"name_es" => "Isla de Norfolk",
				"name_it" => "Isola Norfolk",
				"name_br" => "Ilha Norfolk",
				"name_fr" => "Île de Norfolk",
				"alpha2Code" => "NF",
				"alpha3Code" => "NFK",
				"dialcode" => "672",
				"currenciesCode" => "AUD",
				"currenciesSymbol" => "$",
				"flag" => "🇳🇫"
			],
			[
				"name_en" => "Korea (Democratic People's Republic of)",
				"name_es" => "Corea del Norte",
				"name_it" => "Corea del Nord",
				"name_br" => "Coreia do Norte",
				"name_fr" => "Corée du Nord",
				"alpha2Code" => "KP",
				"alpha3Code" => "PRK",
				"dialcode" => "850",
				"currenciesCode" => "KPW",
				"currenciesSymbol" => "₩",
				"flag" => "🇰🇵"
			],
			[
				"name_en" => "Northern Mariana Islands",
				"name_es" => "Islas Marianas del Norte",
				"name_it" => "Isole Marianne Settentrionali",
				"name_br" => "Ilhas Marianas",
				"name_fr" => "Îles Mariannes du Nord",
				"alpha2Code" => "MP",
				"alpha3Code" => "MNP",
				"dialcode" => "1670",
				"currenciesCode" => "USD",
				"currenciesSymbol" => "$",
				"flag" => "🏳"
			],
			[
				"name_en" => "Norway",
				"name_es" => "Noruega",
				"name_it" => "Norvegia",
				"name_br" => "Noruega",
				"name_fr" => "Norvège",
				"alpha2Code" => "NO",
				"alpha3Code" => "NOR",
				"dialcode" => "47",
				"currenciesCode" => "NOK",
				"currenciesSymbol" => "kr",
				"flag" => "🇳🇴"
			],
			[
				"name_en" => "Oman",
				"name_es" => "Omán",
				"name_it" => "oman",
				"name_br" => "Omã",
				"name_fr" => "Oman",
				"alpha2Code" => "OM",
				"alpha3Code" => "OMN",
				"dialcode" => "968",
				"currenciesCode" => "OMR",
				"currenciesSymbol" => "ر.ع.",
				"flag" => "🇴🇲"
			],
			[
				"name_en" => "Pakistan",
				"name_es" => "Pakistán",
				"name_it" => "Pakistan",
				"name_br" => "Paquistão",
				"name_fr" => "Pakistan",
				"alpha2Code" => "PK",
				"alpha3Code" => "PAK",
				"dialcode" => "92",
				"currenciesCode" => "PKR",
				"currenciesSymbol" => "₨",
				"flag" => "🇵🇰"
			],
			[
				"name_en" => "Palau",
				"name_es" => "Palau",
				"name_it" => "Palau",
				"name_br" => "Palau",
				"name_fr" => "Palaos",
				"alpha2Code" => "PW",
				"alpha3Code" => "PLW",
				"dialcode" => "680",
				"currenciesCode" => "(none)",
				"currenciesSymbol" => "$",
				"flag" => "🇵🇼"
			],
			[
				"name_en" => "Palestine, State of",
				"name_es" => "Palestina",
				"name_it" => "Palestina",
				"name_br" => "Palestina",
				"name_fr" => "Palestine",
				"alpha2Code" => "PS",
				"alpha3Code" => "PSE",
				"dialcode" => "970",
				"currenciesCode" => "ILS",
				"currenciesSymbol" => "₪",
				"flag" => "🇵🇸"
			],
			[
				"name_en" => "Panama",
				"name_es" => "Panamá",
				"name_it" => "Panama",
				"name_br" => "Panamá",
				"name_fr" => "Panama",
				"alpha2Code" => "PA",
				"alpha3Code" => "PAN",
				"dialcode" => "507",
				"currenciesCode" => "PAB",
				"currenciesSymbol" => "B/.",
				"flag" => "🇵🇦"
			],
			[
				"name_en" => "Papua New Guinea",
				"name_es" => "Papúa Nueva Guinea",
				"name_it" => "Papua Nuova Guinea",
				"name_br" => "Papua Nova Guiné",
				"name_fr" => "Papouasie-Nouvelle-Guinée",
				"alpha2Code" => "PG",
				"alpha3Code" => "PNG",
				"dialcode" => "675",
				"currenciesCode" => "PGK",
				"currenciesSymbol" => "K",
				"flag" => "🇵🇬"
			],
			[
				"name_en" => "Paraguay",
				"name_es" => "Paraguay",
				"name_it" => "Paraguay",
				"name_br" => "Paraguai",
				"name_fr" => "Paraguay",
				"alpha2Code" => "PY",
				"alpha3Code" => "PRY",
				"dialcode" => "595",
				"currenciesCode" => "PYG",
				"currenciesSymbol" => "₲",
				"flag" => "🇵🇾"
			],
			[
				"name_en" => "Peru",
				"name_es" => "Perú",
				"name_it" => "Perù",
				"name_br" => "Peru",
				"name_fr" => "Pérou",
				"alpha2Code" => "PE",
				"alpha3Code" => "PER",
				"dialcode" => "51",
				"currenciesCode" => "PEN",
				"currenciesSymbol" => "S/.",
				"flag" => "🇵🇪"
			],
			[
				"name_en" => "Philippines",
				"name_es" => "Filipinas",
				"name_it" => "Filippine",
				"name_br" => "Filipinas",
				"name_fr" => "Philippines",
				"alpha2Code" => "PH",
				"alpha3Code" => "PHL",
				"dialcode" => "63",
				"currenciesCode" => "PHP",
				"currenciesSymbol" => "₱",
				"flag" => "🇵🇭"
			],
			[
				"name_en" => "Pitcairn",
				"name_es" => "Islas Pitcairn",
				"name_it" => "Isole Pitcairn",
				"name_br" => "Ilhas Pitcairn",
				"name_fr" => "Îles Pitcairn",
				"alpha2Code" => "PN",
				"alpha3Code" => "PCN",
				"dialcode" => "64",
				"currenciesCode" => "NZD",
				"currenciesSymbol" => "$",
				"flag" => "🇵🇳"
			],
			[
				"name_en" => "Poland",
				"name_es" => "Polonia",
				"name_it" => "Polonia",
				"name_br" => "Polônia",
				"name_fr" => "Pologne",
				"alpha2Code" => "PL",
				"alpha3Code" => "POL",
				"dialcode" => "48",
				"currenciesCode" => "PLN",
				"currenciesSymbol" => "zł",
				"flag" => "🇵🇱"
			],
			[
				"name_en" => "Portugal",
				"name_es" => "Portugal",
				"name_it" => "Portogallo",
				"name_br" => "Portugal",
				"name_fr" => "Portugal",
				"alpha2Code" => "PT",
				"alpha3Code" => "PRT",
				"dialcode" => "351",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇵🇹"
			],
			[
				"name_en" => "Puerto Rico",
				"name_es" => "Puerto Rico",
				"name_it" => "Porto Rico",
				"name_br" => "Porto Rico",
				"name_fr" => "Porto Rico",
				"alpha2Code" => "PR",
				"alpha3Code" => "PRI",
				"dialcode" => "1787",
				"currenciesCode" => "USD",
				"currenciesSymbol" => "$",
				"flag" => "🇵🇷"
			],
			[
				"name_en" => "Qatar",
				"name_es" => "Catar",
				"name_it" => "Qatar",
				"name_br" => "Catar",
				"name_fr" => "Qatar",
				"alpha2Code" => "QA",
				"alpha3Code" => "QAT",
				"dialcode" => "974",
				"currenciesCode" => "QAR",
				"currenciesSymbol" => "ر.ق",
				"flag" => "🇶🇦"
			],
			[
				"name_en" => "Republic of Kosovo",
				"name_es" => "Kosovo",
				"name_it" => "",
				"name_br" => "Kosovo",
				"name_fr" => "",
				"alpha2Code" => "XK",
				"alpha3Code" => "KOS",
				"dialcode" => "383",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇽🇰"
			],
			[
				"name_en" => "Réunion",
				"name_es" => "Reunión",
				"name_it" => "Riunione",
				"name_br" => "Reunião",
				"name_fr" => "Réunion",
				"alpha2Code" => "RE",
				"alpha3Code" => "REU",
				"dialcode" => "262",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇫🇷"
			],
			[
				"name_en" => "Romania",
				"name_es" => "Rumania",
				"name_it" => "Romania",
				"name_br" => "Romênia",
				"name_fr" => "Roumanie",
				"alpha2Code" => "RO",
				"alpha3Code" => "ROU",
				"dialcode" => "40",
				"currenciesCode" => "RON",
				"currenciesSymbol" => "lei",
				"flag" => "🇷🇴"
			],
			[
				"name_en" => "Russian Federation",
				"name_es" => "Rusia",
				"name_it" => "Russia",
				"name_br" => "Rússia",
				"name_fr" => "Russie",
				"alpha2Code" => "RU",
				"alpha3Code" => "RUS",
				"dialcode" => "7",
				"currenciesCode" => "RUB",
				"currenciesSymbol" => "₽",
				"flag" => "🇷🇺"
			],
			[
				"name_en" => "Rwanda",
				"name_es" => "Ruanda",
				"name_it" => "Ruanda",
				"name_br" => "Ruanda",
				"name_fr" => "Rwanda",
				"alpha2Code" => "RW",
				"alpha3Code" => "RWA",
				"dialcode" => "250",
				"currenciesCode" => "RWF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇷🇼"
			],
			[
				"name_en" => "Saint Barthélemy",
				"name_es" => "San Bartolomé",
				"name_it" => "Antille Francesi",
				"name_br" => "São Bartolomeu",
				"name_fr" => "Saint-Barthélemy",
				"alpha2Code" => "BL",
				"alpha3Code" => "BLM",
				"dialcode" => "590",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇧🇱"
			],
			[
				"name_en" => "Saint Helena, Ascension and Tristan da Cunha",
				"name_es" => "Santa Helena",
				"name_it" => "Sant'Elena",
				"name_br" => "Santa Helena",
				"name_fr" => "Sainte-Hélène",
				"alpha2Code" => "SH",
				"alpha3Code" => "SHN",
				"dialcode" => "290",
				"currenciesCode" => "SHP",
				"currenciesSymbol" => "£",
				"flag" => "🇸🇭"
			],
			[
				"name_en" => "Saint Kitts and Nevis",
				"name_es" => "San Cristóbal y Nieves",
				"name_it" => "Saint Kitts e Nevis",
				"name_br" => "São Cristóvão e Neves",
				"name_fr" => "Saint-Christophe-et-Niévès",
				"alpha2Code" => "KN",
				"alpha3Code" => "KNA",
				"dialcode" => "1869",
				"currenciesCode" => "XCD",
				"currenciesSymbol" => "$",
				"flag" => "🇰🇳"
			],
			[
				"name_en" => "Saint Lucia",
				"name_es" => "Santa Lucía",
				"name_it" => "Santa Lucia",
				"name_br" => "Santa Lúcia",
				"name_fr" => "Saint-Lucie",
				"alpha2Code" => "LC",
				"alpha3Code" => "LCA",
				"dialcode" => "1758",
				"currenciesCode" => "XCD",
				"currenciesSymbol" => "$",
				"flag" => "🇱🇨"
			],
			[
				"name_en" => "Saint Martin (French part)",
				"name_es" => "Saint Martin",
				"name_it" => "Saint Martin",
				"name_br" => "Saint Martin",
				"name_fr" => "Saint-Martin",
				"alpha2Code" => "MF",
				"alpha3Code" => "MAF",
				"dialcode" => "590",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🏳"
			],
			[
				"name_en" => "Saint Pierre and Miquelon",
				"name_es" => "San Pedro y Miquelón",
				"name_it" => "Saint-Pierre e Miquelon",
				"name_br" => "Saint-Pierre e Miquelon",
				"name_fr" => "Saint-Pierre-et-Miquelon",
				"alpha2Code" => "PM",
				"alpha3Code" => "SPM",
				"dialcode" => "508",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇵🇲"
			],
			[
				"name_en" => "Saint Vincent and the Grenadines",
				"name_es" => "San Vicente y Granadinas",
				"name_it" => "Saint Vincent e Grenadine",
				"name_br" => "São Vicente e Granadinas",
				"name_fr" => "Saint-Vincent-et-les-Grenadines",
				"alpha2Code" => "VC",
				"alpha3Code" => "VCT",
				"dialcode" => "1784",
				"currenciesCode" => "XCD",
				"currenciesSymbol" => "$",
				"flag" => "🇻🇨"
			],
			[
				"name_en" => "Samoa",
				"name_es" => "Samoa",
				"name_it" => "Samoa",
				"name_br" => "Samoa",
				"name_fr" => "Samoa",
				"alpha2Code" => "WS",
				"alpha3Code" => "WSM",
				"dialcode" => "685",
				"currenciesCode" => "WST",
				"currenciesSymbol" => "T",
				"flag" => "🇼🇸"
			],
			[
				"name_en" => "San Marino",
				"name_es" => "San Marino",
				"name_it" => "San Marino",
				"name_br" => "San Marino",
				"name_fr" => "Saint-Marin",
				"alpha2Code" => "SM",
				"alpha3Code" => "SMR",
				"dialcode" => "378",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇸🇲"
			],
			[
				"name_en" => "Sao Tome and Principe",
				"name_es" => "Santo Tomé y Príncipe",
				"name_it" => "São Tomé e Príncipe",
				"name_br" => "São Tomé e Príncipe",
				"name_fr" => "Sao Tomé-et-Principe",
				"alpha2Code" => "ST",
				"alpha3Code" => "STP",
				"dialcode" => "239",
				"currenciesCode" => "STD",
				"currenciesSymbol" => "Db",
				"flag" => "🇸🇹"
			],
			[
				"name_en" => "Saudi Arabia",
				"name_es" => "Arabia Saudí",
				"name_it" => "Arabia Saudita",
				"name_br" => "Arábia Saudita",
				"name_fr" => "Arabie Saoudite",
				"alpha2Code" => "SA",
				"alpha3Code" => "SAU",
				"dialcode" => "966",
				"currenciesCode" => "SAR",
				"currenciesSymbol" => "ر.س",
				"flag" => "🇸🇦"
			],
			[
				"name_en" => "Senegal",
				"name_es" => "Senegal",
				"name_it" => "Senegal",
				"name_br" => "Senegal",
				"name_fr" => "Sénégal",
				"alpha2Code" => "SN",
				"alpha3Code" => "SEN",
				"dialcode" => "221",
				"currenciesCode" => "XOF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇸🇳"
			],
			[
				"name_en" => "Serbia",
				"name_es" => "Serbia",
				"name_it" => "Serbia",
				"name_br" => "Sérvia",
				"name_fr" => "Serbie",
				"alpha2Code" => "RS",
				"alpha3Code" => "SRB",
				"dialcode" => "381",
				"currenciesCode" => "RSD",
				"currenciesSymbol" => "дин.",
				"flag" => "🇷🇸"
			],
			[
				"name_en" => "Seychelles",
				"name_es" => "Seychelles",
				"name_it" => "Seychelles",
				"name_br" => "Seicheles",
				"name_fr" => "Seychelles",
				"alpha2Code" => "SC",
				"alpha3Code" => "SYC",
				"dialcode" => "248",
				"currenciesCode" => "SCR",
				"currenciesSymbol" => "₨",
				"flag" => "🇸🇨"
			],
			[
				"name_en" => "Sierra Leone",
				"name_es" => "Sierra Leone",
				"name_it" => "Sierra Leone",
				"name_br" => "Serra Leoa",
				"name_fr" => "Sierra Leone",
				"alpha2Code" => "SL",
				"alpha3Code" => "SLE",
				"dialcode" => "232",
				"currenciesCode" => "SLL",
				"currenciesSymbol" => "Le",
				"flag" => "🇸🇱"
			],
			[
				"name_en" => "Singapore",
				"name_es" => "Singapur",
				"name_it" => "Singapore",
				"name_br" => "Singapura",
				"name_fr" => "Singapour",
				"alpha2Code" => "SG",
				"alpha3Code" => "SGP",
				"dialcode" => "65",
				"currenciesCode" => "BND",
				"currenciesSymbol" => "$",
				"flag" => "🇸🇬"
			],
			[
				"name_en" => "Sint Maarten (Dutch part)",
				"name_es" => "Sint Maarten (parte holandesa)",
				"name_it" => "Saint Martin (parte olandese)",
				"name_br" => "Sint Maarten",
				"name_fr" => "Saint Martin (partie néerlandaise)",
				"alpha2Code" => "SX",
				"alpha3Code" => "SXM",
				"dialcode" => "1721",
				"currenciesCode" => "ANG",
				"currenciesSymbol" => "ƒ",
				"flag" => ""
			],
			[
				"name_en" => "Slovakia",
				"name_es" => "República Eslovaca",
				"name_it" => "Slovacchia",
				"name_br" => "Eslováquia",
				"name_fr" => "Slovaquie",
				"alpha2Code" => "SK",
				"alpha3Code" => "SVK",
				"dialcode" => "421",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇸🇰"
			],
			[
				"name_en" => "Slovenia",
				"name_es" => "Eslovenia",
				"name_it" => "Slovenia",
				"name_br" => "Eslovênia",
				"name_fr" => "Slovénie",
				"alpha2Code" => "SI",
				"alpha3Code" => "SVN",
				"dialcode" => "386",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇸🇮"
			],
			[
				"name_en" => "Solomon Islands",
				"name_es" => "Islas Salomón",
				"name_it" => "Isole Salomone",
				"name_br" => "Ilhas Salomão",
				"name_fr" => "Îles Salomon",
				"alpha2Code" => "SB",
				"alpha3Code" => "SLB",
				"dialcode" => "677",
				"currenciesCode" => "SBD",
				"currenciesSymbol" => "$",
				"flag" => "🇸🇧"
			],
			[
				"name_en" => "Somalia",
				"name_es" => "Somalia",
				"name_it" => "Somalia",
				"name_br" => "Somália",
				"name_fr" => "Somalie",
				"alpha2Code" => "SO",
				"alpha3Code" => "SOM",
				"dialcode" => "252",
				"currenciesCode" => "SOS",
				"currenciesSymbol" => "Sh",
				"flag" => "🇸🇴"
			],
			[
				"name_en" => "South Africa",
				"name_es" => "República de Sudáfrica",
				"name_it" => "Sud Africa",
				"name_br" => "República Sul-Africana",
				"name_fr" => "Afrique du Sud",
				"alpha2Code" => "ZA",
				"alpha3Code" => "ZAF",
				"dialcode" => "27",
				"currenciesCode" => "ZAR",
				"currenciesSymbol" => "R",
				"flag" => "🇿🇦"
			],
			[
				"name_en" => "South Georgia and the South Sandwich Islands",
				"name_es" => "Islas Georgias del Sur y Sandwich del Sur",
				"name_it" => "Georgia del Sud e Isole Sandwich Meridionali",
				"name_br" => "Ilhas Geórgias do Sul e Sandwich do Sul",
				"name_fr" => "Géorgie du Sud-et-les Îles Sandwich du Sud",
				"alpha2Code" => "GS",
				"alpha3Code" => "SGS",
				"dialcode" => "500",
				"currenciesCode" => "GBP",
				"currenciesSymbol" => "£",
				"flag" => "🇬🇸"
			],
			[
				"name_en" => "Korea (Republic of)",
				"name_es" => "Corea del Sur",
				"name_it" => "Corea del Sud",
				"name_br" => "Coreia do Sul",
				"name_fr" => "Corée du Sud",
				"alpha2Code" => "KR",
				"alpha3Code" => "KOR",
				"dialcode" => "82",
				"currenciesCode" => "KRW",
				"currenciesSymbol" => "₩",
				"flag" => "🇰🇷"
			],
			[
				"name_en" => "South Sudan",
				"name_es" => "Sudán del Sur",
				"name_it" => "Sudan del sud",
				"name_br" => "Sudão do Sul",
				"name_fr" => "Soudan du Sud",
				"alpha2Code" => "SS",
				"alpha3Code" => "SSD",
				"dialcode" => "211",
				"currenciesCode" => "SSP",
				"currenciesSymbol" => "£",
				"flag" => "🇸🇸"
			],
			[
				"name_en" => "Spain",
				"name_es" => "España",
				"name_it" => "Spagna",
				"name_br" => "Espanha",
				"name_fr" => "Espagne",
				"alpha2Code" => "ES",
				"alpha3Code" => "ESP",
				"dialcode" => "34",
				"currenciesCode" => "EUR",
				"currenciesSymbol" => "€",
				"flag" => "🇪🇸"
			],
			[
				"name_en" => "Sri Lanka",
				"name_es" => "Sri Lanka",
				"name_it" => "Sri Lanka",
				"name_br" => "Sri Lanka",
				"name_fr" => "Sri Lanka",
				"alpha2Code" => "LK",
				"alpha3Code" => "LKA",
				"dialcode" => "94",
				"currenciesCode" => "LKR",
				"currenciesSymbol" => "Rs",
				"flag" => "🇱🇰"
			],
			[
				"name_en" => "Sudan",
				"name_es" => "Sudán",
				"name_it" => "Sudan",
				"name_br" => "Sudão",
				"name_fr" => "Soudan",
				"alpha2Code" => "SD",
				"alpha3Code" => "SDN",
				"dialcode" => "249",
				"currenciesCode" => "SDG",
				"currenciesSymbol" => "ج.س.",
				"flag" => "🇸🇩"
			],
			[
				"name_en" => "Suriname",
				"name_es" => "Surinam",
				"name_it" => "Suriname",
				"name_br" => "Suriname",
				"name_fr" => "Surinam",
				"alpha2Code" => "SR",
				"alpha3Code" => "SUR",
				"dialcode" => "597",
				"currenciesCode" => "SRD",
				"currenciesSymbol" => "$",
				"flag" => "🇸🇷"
			],
			[
				"name_en" => "Svalbard and Jan Mayen",
				"name_es" => "Islas Svalbard y Jan Mayen",
				"name_it" => "Svalbard e Jan Mayen",
				"name_br" => "Svalbard",
				"name_fr" => "Svalbard et Jan Mayen",
				"alpha2Code" => "SJ",
				"alpha3Code" => "SJM",
				"dialcode" => "4779",
				"currenciesCode" => "NOK",
				"currenciesSymbol" => "kr",
				"flag" => "🇩🇰"
			],
			[
				"name_en" => "Swaziland",
				"name_es" => "Suazilandia",
				"name_it" => "Swaziland",
				"name_br" => "Suazilândia",
				"name_fr" => "Swaziland",
				"alpha2Code" => "SZ",
				"alpha3Code" => "SWZ",
				"dialcode" => "268",
				"currenciesCode" => "SZL",
				"currenciesSymbol" => "L",
				"flag" => "🇸🇿"
			],
			[
				"name_en" => "Sweden",
				"name_es" => "Suecia",
				"name_it" => "Svezia",
				"name_br" => "Suécia",
				"name_fr" => "Suède",
				"alpha2Code" => "SE",
				"alpha3Code" => "SWE",
				"dialcode" => "46",
				"currenciesCode" => "SEK",
				"currenciesSymbol" => "kr",
				"flag" => "🇸🇪"
			],
			[
				"name_en" => "Switzerland",
				"name_es" => "Suiza",
				"name_it" => "Svizzera",
				"name_br" => "Suíça",
				"name_fr" => "Suisse",
				"alpha2Code" => "CH",
				"alpha3Code" => "CHE",
				"dialcode" => "41",
				"currenciesCode" => "CHF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇨🇭"
			],
			[
				"name_en" => "Syrian Arab Republic",
				"name_es" => "Siria",
				"name_it" => "Siria",
				"name_br" => "Síria",
				"name_fr" => "Syrie",
				"alpha2Code" => "SY",
				"alpha3Code" => "SYR",
				"dialcode" => "963",
				"currenciesCode" => "SYP",
				"currenciesSymbol" => "£",
				"flag" => "🇸🇾"
			],
			[
				"name_en" => "Taiwan",
				"name_es" => "Taiwán",
				"name_it" => "Taiwan",
				"name_br" => "Taiwan",
				"name_fr" => "Taïwan",
				"alpha2Code" => "TW",
				"alpha3Code" => "TWN",
				"dialcode" => "886",
				"currenciesCode" => "TWD",
				"currenciesSymbol" => "$",
				"flag" => "🇹🇼"
			],
			[
				"name_en" => "Tajikistan",
				"name_es" => "Tayikistán",
				"name_it" => "Tagikistan",
				"name_br" => "Tajiquistão",
				"name_fr" => "Tadjikistan",
				"alpha2Code" => "TJ",
				"alpha3Code" => "TJK",
				"dialcode" => "992",
				"currenciesCode" => "TJS",
				"currenciesSymbol" => "ЅМ",
				"flag" => "🇹🇯"
			],
			[
				"name_en" => "Tanzania, United Republic of",
				"name_es" => "Tanzania",
				"name_it" => "Tanzania",
				"name_br" => "Tanzânia",
				"name_fr" => "Tanzanie",
				"alpha2Code" => "TZ",
				"alpha3Code" => "TZA",
				"dialcode" => "255",
				"currenciesCode" => "TZS",
				"currenciesSymbol" => "Sh",
				"flag" => "🇹🇿"
			],
			[
				"name_en" => "Thailand",
				"name_es" => "Tailandia",
				"name_it" => "Tailandia",
				"name_br" => "Tailândia",
				"name_fr" => "Thaïlande",
				"alpha2Code" => "TH",
				"alpha3Code" => "THA",
				"dialcode" => "66",
				"currenciesCode" => "THB",
				"currenciesSymbol" => "฿",
				"flag" => "🇹🇭"
			],
			[
				"name_en" => "Timor-Leste",
				"name_es" => "Timor Oriental",
				"name_it" => "Timor Est",
				"name_br" => "Timor Leste",
				"name_fr" => "Timor oriental",
				"alpha2Code" => "TL",
				"alpha3Code" => "TLS",
				"dialcode" => "670",
				"currenciesCode" => "USD",
				"currenciesSymbol" => "$",
				"flag" => "🇹🇱"
			],
			[
				"name_en" => "Togo",
				"name_es" => "Togo",
				"name_it" => "Togo",
				"name_br" => "Togo",
				"name_fr" => "Togo",
				"alpha2Code" => "TG",
				"alpha3Code" => "TGO",
				"dialcode" => "228",
				"currenciesCode" => "XOF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇹🇬"
			],
			[
				"name_en" => "Tokelau",
				"name_es" => "Islas Tokelau",
				"name_it" => "Isole Tokelau",
				"name_br" => "Tokelau",
				"name_fr" => "Tokelau",
				"alpha2Code" => "TK",
				"alpha3Code" => "TKL",
				"dialcode" => "690",
				"currenciesCode" => "NZD",
				"currenciesSymbol" => "$",
				"flag" => "🇹🇰"
			],
			[
				"name_en" => "Tonga",
				"name_es" => "Tonga",
				"name_it" => "Tonga",
				"name_br" => "Tonga",
				"name_fr" => "Tonga",
				"alpha2Code" => "TO",
				"alpha3Code" => "TON",
				"dialcode" => "676",
				"currenciesCode" => "TOP",
				"currenciesSymbol" => "T$",
				"flag" => "🇹🇴"
			],
			[
				"name_en" => "Trinidad and Tobago",
				"name_es" => "Trinidad y Tobago",
				"name_it" => "Trinidad e Tobago",
				"name_br" => "Trinidad e Tobago",
				"name_fr" => "Trinité et Tobago",
				"alpha2Code" => "TT",
				"alpha3Code" => "TTO",
				"dialcode" => "1868",
				"currenciesCode" => "TTD",
				"currenciesSymbol" => "$",
				"flag" => "🇹🇹"
			],
			[
				"name_en" => "Tunisia",
				"name_es" => "Túnez",
				"name_it" => "Tunisia",
				"name_br" => "Tunísia",
				"name_fr" => "Tunisie",
				"alpha2Code" => "TN",
				"alpha3Code" => "TUN",
				"dialcode" => "216",
				"currenciesCode" => "TND",
				"currenciesSymbol" => "د.ت",
				"flag" => "🇹🇳"
			],
			[
				"name_en" => "Turkey",
				"name_es" => "Turquía",
				"name_it" => "Turchia",
				"name_br" => "Turquia",
				"name_fr" => "Turquie",
				"alpha2Code" => "TR",
				"alpha3Code" => "TUR",
				"dialcode" => "90",
				"currenciesCode" => "TRY",
				"currenciesSymbol" => "",
				"flag" => "🇹🇷"
			],
			[
				"name_en" => "Turkmenistan",
				"name_es" => "Turkmenistán",
				"name_it" => "Turkmenistan",
				"name_br" => "Turcomenistão",
				"name_fr" => "Turkménistan",
				"alpha2Code" => "TM",
				"alpha3Code" => "TKM",
				"dialcode" => "993",
				"currenciesCode" => "TMT",
				"currenciesSymbol" => "m",
				"flag" => "🇹🇲"
			],
			[
				"name_en" => "Turks and Caicos Islands",
				"name_es" => "Islas Turks y Caicos",
				"name_it" => "Isole Turks e Caicos",
				"name_br" => "Ilhas Turcas e Caicos",
				"name_fr" => "Îles Turques-et-Caïques",
				"alpha2Code" => "TC",
				"alpha3Code" => "TCA",
				"dialcode" => "1649",
				"currenciesCode" => "USD",
				"currenciesSymbol" => "$",
				"flag" => "🇹🇨"
			],
			[
				"name_en" => "Tuvalu",
				"name_es" => "Tuvalu",
				"name_it" => "Tuvalu",
				"name_br" => "Tuvalu",
				"name_fr" => "Tuvalu",
				"alpha2Code" => "TV",
				"alpha3Code" => "TUV",
				"dialcode" => "688",
				"currenciesCode" => "AUD",
				"currenciesSymbol" => "$",
				"flag" => "🇹🇻"
			],
			[
				"name_en" => "Uganda",
				"name_es" => "Uganda",
				"name_it" => "Uganda",
				"name_br" => "Uganda",
				"name_fr" => "Uganda",
				"alpha2Code" => "UG",
				"alpha3Code" => "UGA",
				"dialcode" => "256",
				"currenciesCode" => "UGX",
				"currenciesSymbol" => "Sh",
				"flag" => "🇺🇬"
			],
			[
				"name_en" => "Ukraine",
				"name_es" => "Ucrania",
				"name_it" => "Ucraina",
				"name_br" => "Ucrânia",
				"name_fr" => "Ukraine",
				"alpha2Code" => "UA",
				"alpha3Code" => "UKR",
				"dialcode" => "380",
				"currenciesCode" => "UAH",
				"currenciesSymbol" => "₴",
				"flag" => "🇺🇦"
			],
			[
				"name_en" => "United Arab Emirates",
				"name_es" => "Emiratos Árabes Unidos",
				"name_it" => "Emirati Arabi Uniti",
				"name_br" => "Emirados árabes Unidos",
				"name_fr" => "Émirats arabes unis",
				"alpha2Code" => "AE",
				"alpha3Code" => "ARE",
				"dialcode" => "971",
				"currenciesCode" => "AED",
				"currenciesSymbol" => "د.إ",
				"flag" => "🇦🇪"
			],
			[
				"name_en" => "United Kingdom of Great Britain and Northern Ireland",
				"name_es" => "Reino Unido",
				"name_it" => "Regno Unito",
				"name_br" => "Reino Unido",
				"name_fr" => "Royaume-Uni",
				"alpha2Code" => "GB",
				"alpha3Code" => "GBR",
				"dialcode" => "44",
				"currenciesCode" => "GBP",
				"currenciesSymbol" => "£",
				"flag" => "🇬🇧"
			],
			[
				"name_en" => "United States of America",
				"name_es" => "Estados Unidos",
				"name_it" => "Stati Uniti D'America",
				"name_br" => "Estados Unidos",
				"name_fr" => "États-Unis",
				"alpha2Code" => "US",
				"alpha3Code" => "USA",
				"dialcode" => "1",
				"currenciesCode" => "USD",
				"currenciesSymbol" => "$",
				"flag" => "🇺🇸"
			],
			[
				"name_en" => "Uruguay",
				"name_es" => "Uruguay",
				"name_it" => "Uruguay",
				"name_br" => "Uruguai",
				"name_fr" => "Uruguay",
				"alpha2Code" => "UY",
				"alpha3Code" => "URY",
				"dialcode" => "598",
				"currenciesCode" => "UYU",
				"currenciesSymbol" => "$",
				"flag" => "🇺🇾"
			],
			[
				"name_en" => "Uzbekistan",
				"name_es" => "Uzbekistán",
				"name_it" => "Uzbekistan",
				"name_br" => "Uzbequistão",
				"name_fr" => "Ouzbékistan",
				"alpha2Code" => "UZ",
				"alpha3Code" => "UZB",
				"dialcode" => "998",
				"currenciesCode" => "UZS",
				"currenciesSymbol" => "",
				"flag" => "🇺🇿"
			],
			[
				"name_en" => "Vanuatu",
				"name_es" => "Vanuatu",
				"name_it" => "Vanuatu",
				"name_br" => "Vanuatu",
				"name_fr" => "Vanuatu",
				"alpha2Code" => "VU",
				"alpha3Code" => "VUT",
				"dialcode" => "678",
				"currenciesCode" => "VUV",
				"currenciesSymbol" => "Vt",
				"flag" => "🇻🇺"
			],
			[
				"name_en" => "Venezuela (Bolivarian Republic of)",
				"name_es" => "Venezuela",
				"name_it" => "Venezuela",
				"name_br" => "Venezuela",
				"name_fr" => "Venezuela",
				"alpha2Code" => "VE",
				"alpha3Code" => "VEN",
				"dialcode" => "58",
				"currenciesCode" => "VEF",
				"currenciesSymbol" => "Bs F",
				"flag" => "🇻🇪"
			],
			[
				"name_en" => "Viet Nam",
				"name_es" => "Vietnam",
				"name_it" => "Vietnam",
				"name_br" => "Vietnã",
				"name_fr" => "Viêt Nam",
				"alpha2Code" => "VN",
				"alpha3Code" => "VNM",
				"dialcode" => "84",
				"currenciesCode" => "VND",
				"currenciesSymbol" => "₫",
				"flag" => "🇻🇳"
			],
			[
				"name_en" => "Wallis and Futuna",
				"name_es" => "Wallis y Futuna",
				"name_it" => "Wallis e Futuna",
				"name_br" => "Wallis e Futuna",
				"name_fr" => "Wallis-et-Futuna",
				"alpha2Code" => "WF",
				"alpha3Code" => "WLF",
				"dialcode" => "681",
				"currenciesCode" => "XPF",
				"currenciesSymbol" => "Fr",
				"flag" => "🇼🇫"
			],
			[
				"name_en" => "Western Sahara",
				"name_es" => "Sahara Occidental",
				"name_it" => "Sahara Occidentale",
				"name_br" => "Saara Ocidental",
				"name_fr" => "Sahara Occidental",
				"alpha2Code" => "EH",
				"alpha3Code" => "ESH",
				"dialcode" => "212",
				"currenciesCode" => "MAD",
				"currenciesSymbol" => "د.م.",
				"flag" => ""
			],
			[
				"name_en" => "Yemen",
				"name_es" => "Yemen",
				"name_it" => "Yemen",
				"name_br" => "Iêmen",
				"name_fr" => "Yémen",
				"alpha2Code" => "YE",
				"alpha3Code" => "YEM",
				"dialcode" => "967",
				"currenciesCode" => "YER",
				"currenciesSymbol" => "﷼",
				"flag" => "🇾🇪"
			],
			[
				"name_en" => "Zambia",
				"name_es" => "Zambia",
				"name_it" => "Zambia",
				"name_br" => "Zâmbia",
				"name_fr" => "Zambie",
				"alpha2Code" => "ZM",
				"alpha3Code" => "ZMB",
				"dialcode" => "260",
				"currenciesCode" => "ZMW",
				"currenciesSymbol" => "ZK",
				"flag" => "🇿🇲"
			],
			[
				"name_en" => "Zimbabwe",
				"name_es" => "Zimbabue",
				"name_it" => "Zimbabwe",
				"name_br" => "Zimbabwe",
				"name_fr" => "Zimbabwe",
				"alpha2Code" => "ZW",
				"alpha3Code" => "ZWE",
				"dialcode" => "263",
				"currenciesCode" => "BWP",
				"currenciesSymbol" => "P",
				"flag" => "🇿🇼"
			]
		];

   
		DB::table('countries')->insert($countries);
	}
}
